failure-threshold: info   # error|warning|info|style|ignore|none

ignored:
  - DL3008                # pin versions in apt
  - DL3013                # pin versions in pip
  - DL3014                # apt-get install -y
  - DL3015                # apt-get install --no-install-recommends
  - DL3018                # pin versions in apk
  - DL3042                # pip --no-cache-dir

trustedRegistries:
  - docker.io
  - "*.gcr.io"
  - localhost:32000
